Store ENV variables to serverSettings collection.
lowcoder-org/lowcoder pull request #893
Opened 2024-05-17 23:07 UTC by th37rose

## Proposed changes
Store ENV variables to serverSettings collection.
Create new api endpoint: /api/serverSettings

## Types of changes
What types of changes does your code introduce to Lowcoder?  
_Put an `x` in the boxes that apply._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist
You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code.  
_Put an `x` in the boxes that apply._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

2024-05-18 19:04 UTC, ludomikula requested changes

2024-05-19 13:53 UTC, th37rose commented on server/api-service/lowcoder-domain/src/main/java/org/lowcoder/domain/serversetting/service/ServerSettingServiceImpl.java
> +                .filter(key -> key.contains("LOWCODER_"))
.filter(key -> key.contains("LOWCODER_"))

This line works for it.

2024-05-20 08:13 UTC, ludomikula commented on server/api-service/lowcoder-domain/src/main/java/org/lowcoder/domain/serversetting/service/ServerSettingServiceImpl.java
> +                .filter(key -> key.contains("LOWCODER_"))
Yes, however it also matches **SOME_LOWCODER_VARIABLE**.

2024-05-20 08:40 UTC, th37rose commented on server/api-service/lowcoder-domain/src/main/java/org/lowcoder/domain/serversetting/service/ServerSettingServiceImpl.java
> +                .filter(key -> key.contains("LOWCODER_"))
Changed from `.contains()` to `.startsWith()`

2024-05-20 10:00 UTC, ludomikula approved these changes

2024-05-20 10:01 UTC, merged